{"uid":"7986c0a89a4854a3","name":"Успешная регистрация студента с полными данными","fullName":"tests.test_page_object#test_complete_do","historyId":"f8638fbca7d3fb3e8502a78a75c9b25b","time":{"start":1753092514568,"stop":1753092521156,"duration":6588},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception\nStacktrace:\n#0 0x558e932d223a <unknown>\n#1 0x558e92d7cab0 <unknown>\n#2 0x558e92db78ac <unknown>\n#3 0x558e92db2307 <unknown>\n#4 0x558e92e02696 <unknown>\n#5 0x558e92e01d56 <unknown>\n#6 0x558e92df3f73 <unknown>\n#7 0x558e92dc0aeb <unknown>\n#8 0x558e92dc1751 <unknown>\n#9 0x558e93296b4b <unknown>\n#10 0x558e9329a929 <unknown>\n#11 0x558e9327d929 <unknown>\n#12 0x558e9329b4e8 <unknown>\n#13 0x558e932620df <unknown>\n#14 0x558e932bf8e8 <unknown>\n#15 0x558e932bfac6 <unknown>\n#16 0x558e932d1556 <unknown>\n#17 0x7fc1d829caa4 <unknown>\n#18 0x7fc1d8329c3c <unknown>","statusTrace":"@allure.tag(\"web\")\n    @allure.title(\"Успешная регистрация студента с полными данными\")\n    @allure.label(\"owner\", \"Max Razzhivin\")\n    @allure.feature(\"Форма для заполнения студентом своих данных\")\n    @allure.story(\"Форма корректно заполняется и результаты корректные\")\n    @allure.link(\"https://demoqa.com/automation-practice-form\", \"Test\")\n    @allure.severity(Severity.CRITICAL)\n    def test_complete_do():\n        # GIVEN:\n        registration_page = RegistrationPage()\n>       registration_page.open()\n\ntests/test_page_object.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/registration_page.py:21: in open\n    browser.open('/automation-practice-form')\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/_browser.py:93: in open\n    self.config._executor.get_url(relative_or_absolute_url)\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/configuration.py:263: in get_url\n    self.config._driver_get_url_strategy(self.config)(url)\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/configuration.py:178: in get\n    driver = config.driver\n             ^^^^^^^^^^^^^\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/configuration.py:305: in __get__\n    driver = config.build_driver_strategy(config)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/configuration.py:129: in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/configuration.py:66: in build_chrome\n    return Chrome(\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py:47: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py:69: in __init__\n    super().__init__(command_executor=executor, options=options)\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:261: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:362: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:454: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f29a21001a0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: probably user data d...\\\\n#16 0x558e932d1556 \\\\u003Cunknown>\\\\n#17 0x7fc1d829caa4 \\\\u003Cunknown>\\\\n#18 0x7fc1d8329c3c \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                try:\n                    value = json.loads(value_json)\n                    if isinstance(value, dict):\n                        if len(value) == 1:\n                            value = value[\"value\"]\n                        status = value.get(\"error\", None)\n                        if not status:\n                            status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                            message = value.get(\"value\") or value.get(\"message\")\n                            if not isinstance(message, str):\n                                value = message\n                                message = message.get(\"message\")\n                        else:\n                            message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception\nE       Stacktrace:\nE       #0 0x558e932d223a <unknown>\nE       #1 0x558e92d7cab0 <unknown>\nE       #2 0x558e92db78ac <unknown>\nE       #3 0x558e92db2307 <unknown>\nE       #4 0x558e92e02696 <unknown>\nE       #5 0x558e92e01d56 <unknown>\nE       #6 0x558e92df3f73 <unknown>\nE       #7 0x558e92dc0aeb <unknown>\nE       #8 0x558e92dc1751 <unknown>\nE       #9 0x558e93296b4b <unknown>\nE       #10 0x558e9329a929 <unknown>\nE       #11 0x558e9327d929 <unknown>\nE       #12 0x558e9329b4e8 <unknown>\nE       #13 0x558e932620df <unknown>\nE       #14 0x558e932bf8e8 <unknown>\nE       #15 0x558e932bfac6 <unknown>\nE       #16 0x558e932d1556 <unknown>\nE       #17 0x7fc1d829caa4 <unknown>\nE       #18 0x7fc1d8329c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py:232: SessionNotCreatedException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"browser_management","time":{"start":1753092512567,"stop":1753092514567,"duration":2000},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception\nStacktrace:\n#0 0x558e932d223a <unknown>\n#1 0x558e92d7cab0 <unknown>\n#2 0x558e92db78ac <unknown>\n#3 0x558e92db2307 <unknown>\n#4 0x558e92e02696 <unknown>\n#5 0x558e92e01d56 <unknown>\n#6 0x558e92df3f73 <unknown>\n#7 0x558e92dc0aeb <unknown>\n#8 0x558e92dc1751 <unknown>\n#9 0x558e93296b4b <unknown>\n#10 0x558e9329a929 <unknown>\n#11 0x558e9327d929 <unknown>\n#12 0x558e9329b4e8 <unknown>\n#13 0x558e932620df <unknown>\n#14 0x558e932bf8e8 <unknown>\n#15 0x558e932bfac6 <unknown>\n#16 0x558e932d1556 <unknown>\n#17 0x7fc1d829caa4 <unknown>\n#18 0x7fc1d8329c3c <unknown>","statusTrace":"@allure.tag(\"web\")\n    @allure.title(\"Успешная регистрация студента с полными данными\")\n    @allure.label(\"owner\", \"Max Razzhivin\")\n    @allure.feature(\"Форма для заполнения студентом своих данных\")\n    @allure.story(\"Форма корректно заполняется и результаты корректные\")\n    @allure.link(\"https://demoqa.com/automation-practice-form\", \"Test\")\n    @allure.severity(Severity.CRITICAL)\n    def test_complete_do():\n        # GIVEN:\n        registration_page = RegistrationPage()\n>       registration_page.open()\n\ntests/test_page_object.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/registration_page.py:21: in open\n    browser.open('/automation-practice-form')\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/_browser.py:93: in open\n    self.config._executor.get_url(relative_or_absolute_url)\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/configuration.py:263: in get_url\n    self.config._driver_get_url_strategy(self.config)(url)\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/configuration.py:178: in get\n    driver = config.driver\n             ^^^^^^^^^^^^^\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/configuration.py:305: in __get__\n    driver = config.build_driver_strategy(config)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/configuration.py:129: in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/configuration.py:66: in build_chrome\n    return Chrome(\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py:47: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py:69: in __init__\n    super().__init__(command_executor=executor, options=options)\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:261: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:362: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:454: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f29a21001a0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: probably user data d...\\\\n#16 0x558e932d1556 \\\\u003Cunknown>\\\\n#17 0x7fc1d829caa4 \\\\u003Cunknown>\\\\n#18 0x7fc1d8329c3c \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                try:\n                    value = json.loads(value_json)\n                    if isinstance(value, dict):\n                        if len(value) == 1:\n                            value = value[\"value\"]\n                        status = value.get(\"error\", None)\n                        if not status:\n                            status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                            message = value.get(\"value\") or value.get(\"message\")\n                            if not isinstance(message, str):\n                                value = message\n                                message = message.get(\"message\")\n                        else:\n                            message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception\nE       Stacktrace:\nE       #0 0x558e932d223a <unknown>\nE       #1 0x558e92d7cab0 <unknown>\nE       #2 0x558e92db78ac <unknown>\nE       #3 0x558e92db2307 <unknown>\nE       #4 0x558e92e02696 <unknown>\nE       #5 0x558e92e01d56 <unknown>\nE       #6 0x558e92df3f73 <unknown>\nE       #7 0x558e92dc0aeb <unknown>\nE       #8 0x558e92dc1751 <unknown>\nE       #9 0x558e93296b4b <unknown>\nE       #10 0x558e9329a929 <unknown>\nE       #11 0x558e9327d929 <unknown>\nE       #12 0x558e9329b4e8 <unknown>\nE       #13 0x558e932620df <unknown>\nE       #14 0x558e932bf8e8 <unknown>\nE       #15 0x558e932bfac6 <unknown>\nE       #16 0x558e932d1556 <unknown>\nE       #17 0x7fc1d829caa4 <unknown>\nE       #18 0x7fc1d8329c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py:232: SessionNotCreatedException","steps":[{"name":"Открываем браузер и удаляем рекламу","time":{"start":1753092514568,"stop":1753092521153,"duration":6585},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception\nStacktrace:\n#0 0x558e932d223a <unknown>\n#1 0x558e92d7cab0 <unknown>\n#2 0x558e92db78ac <unknown>\n#3 0x558e92db2307 <unknown>\n#4 0x558e92e02696 <unknown>\n#5 0x558e92e01d56 <unknown>\n#6 0x558e92df3f73 <unknown>\n#7 0x558e92dc0aeb <unknown>\n#8 0x558e92dc1751 <unknown>\n#9 0x558e93296b4b <unknown>\n#10 0x558e9329a929 <unknown>\n#11 0x558e9327d929 <unknown>\n#12 0x558e9329b4e8 <unknown>\n#13 0x558e932620df <unknown>\n#14 0x558e932bf8e8 <unknown>\n#15 0x558e932bfac6 <unknown>\n#16 0x558e932d1556 <unknown>\n#17 0x7fc1d829caa4 <unknown>\n#18 0x7fc1d8329c3c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/Selene-PageObject/Selene-PageObject/pages/registration_page.py\", line 21, in open\n    browser.open('/automation-practice-form')\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/_browser.py\", line 93, in open\n    self.config._executor.get_url(relative_or_absolute_url)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 263, in get_url\n    self.config._driver_get_url_strategy(self.config)(url)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 178, in get\n    driver = config.driver\n             ^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 305, in __get__\n    driver = config.build_driver_strategy(config)\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 129, in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n           ~~~~~~~~~~~~~~~~~\n    ...<32 lines>...\n        )\n        ~\n    )()\n    ~^^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 66, in build_chrome\n    return Chrome(\n        service=config.driver_service or ChromeService(),\n        options=config.driver_options,\n    )\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py\", line 47, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        browser_name=DesiredCapabilities.CHROME[\"browserName\"],\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        keep_alive=keep_alive,\n        ^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py\", line 69, in __init__\n    super().__init__(command_executor=executor, options=options)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 261, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 362, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 454, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"9f447f4a072753df","name":"stdout","source":"9f447f4a072753df.txt","type":"text/plain","size":58}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":1,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"browser_management::0","time":{"start":1753092521235,"stop":1753092521437,"duration":202},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception\nStacktrace:\n#0 0x55c726cc623a <unknown>\n#1 0x55c726770ab0 <unknown>\n#2 0x55c7267ab8ac <unknown>\n#3 0x55c7267a6307 <unknown>\n#4 0x55c7267f6696 <unknown>\n#5 0x55c7267f5d56 <unknown>\n#6 0x55c7267e7f73 <unknown>\n#7 0x55c7267b4aeb <unknown>\n#8 0x55c7267b5751 <unknown>\n#9 0x55c726c8ab4b <unknown>\n#10 0x55c726c8e929 <unknown>\n#11 0x55c726c71929 <unknown>\n#12 0x55c726c8f4e8 <unknown>\n#13 0x55c726c560df <unknown>\n#14 0x55c726cb38e8 <unknown>\n#15 0x55c726cb3ac6 <unknown>\n#16 0x55c726cc5556 <unknown>\n#17 0x7f1f7169caa4 <unknown>\n#18 0x7f1f71729c3c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/_pytest/fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"/home/runner/work/Selene-PageObject/Selene-PageObject/tests/conftest.py\", line 89, in browser_management\n    attach.add_screenshot(browser)\n    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/home/runner/work/Selene-PageObject/Selene-PageObject/utils/attach.py\", line 11, in add_screenshot\n    png = browser.driver.get_screenshot_as_png()\n          ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/_browser.py\", line 34, in driver\n    return self.config.driver\n           ^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 305, in __get__\n    driver = config.build_driver_strategy(config)\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 129, in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n           ~~~~~~~~~~~~~~~~~\n    ...<32 lines>...\n        )\n        ~\n    )()\n    ~^^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 66, in build_chrome\n    return Chrome(\n        service=config.driver_service or ChromeService(),\n        options=config.driver_options,\n    )\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py\", line 47, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        browser_name=DesiredCapabilities.CHROME[\"browserName\"],\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        keep_alive=keep_alive,\n        ^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py\", line 69, in __init__\n    super().__init__(command_executor=executor, options=options)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 261, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 362, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 454, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"labels":[{"name":"tag","value":"web"},{"name":"story","value":"Форма корректно заполняется и результаты корректные"},{"name":"feature","value":"Форма для заполнения студентом своих данных"},{"name":"owner","value":"Max Razzhivin"},{"name":"severity","value":"critical"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_page_object"},{"name":"host","value":"pkrvmq0rgcvqdmg"},{"name":"thread","value":"4482-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_page_object"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[{"name":"https://demoqa.com/automation-practice-form","url":"https://demoqa.com/automation-practice-form","type":"Test"}],"hidden":false,"retry":false,"extra":{"severity":"critical","owner":"Max Razzhivin","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":1,"unknown":0,"total":3},"items":[{"uid":"a82aea78443c240e","reportUrl":"https://MaxRazzhivin.github.io/Selene-PageObject/26//#testresult/a82aea78443c240e","status":"broken","statusDetails":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception\nStacktrace:\n#0 0x5651fe85723a <unknown>\n#1 0x5651fe301ab0 <unknown>\n#2 0x5651fe33c8ac <unknown>\n#3 0x5651fe337307 <unknown>\n#4 0x5651fe387696 <unknown>\n#5 0x5651fe386d56 <unknown>\n#6 0x5651fe378f73 <unknown>\n#7 0x5651fe345aeb <unknown>\n#8 0x5651fe346751 <unknown>\n#9 0x5651fe81bb4b <unknown>\n#10 0x5651fe81f929 <unknown>\n#11 0x5651fe802929 <unknown>\n#12 0x5651fe8204e8 <unknown>\n#13 0x5651fe7e70df <unknown>\n#14 0x5651fe8448e8 <unknown>\n#15 0x5651fe844ac6 <unknown>\n#16 0x5651fe856556 <unknown>\n#17 0x7f304109caa4 <unknown>\n#18 0x7f3041129c3c <unknown>","time":{"start":1753091881611,"stop":1753091887354,"duration":5743}},{"uid":"59f61d7fed5b16bb","reportUrl":"https://MaxRazzhivin.github.io/Selene-PageObject/25//#testresult/59f61d7fed5b16bb","status":"passed","time":{"start":1753091477730,"stop":1753091495187,"duration":17457}}]},"tags":["web"]},"source":"7986c0a89a4854a3.json","parameterValues":[]}